name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.14.0"
          rebar3-version: "3"

      - name: Cache Gleam packages
        uses: actions/cache@v5
        with:
          path: build/packages
          key: gleam-packages-${{ hashFiles('manifest.toml') }}

      - name: Download dependencies
        run: gleam deps download

      - name: Test
        run: gleam test

      - name: Check formatting
        run: gleam format --check src test
